# Generated by Django 5.1.2 on 2024-10-24 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyzer', '0002_predictiondata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictiondata',
            old_name='model_used',
            new_name='model_type',
        ),
    ]
